/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as ObjectsImport } from './routes/objects'
import { Route as NotesNoteIdImport } from './routes/notes/$noteId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ObjectsRoute = ObjectsImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NotesNoteIdRoute = NotesNoteIdImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/objects': {
      id: '/objects'
      path: '/objects'
      fullPath: '/objects'
      preLoaderRoute: typeof ObjectsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/objects': typeof ObjectsRoute
  '/settings': typeof SettingsRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/objects': typeof ObjectsRoute
  '/settings': typeof SettingsRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/objects': typeof ObjectsRoute
  '/settings': typeof SettingsRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/objects' | '/settings' | '/notes/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/objects' | '/settings' | '/notes/$noteId'
  id: '__root__' | '/' | '/objects' | '/settings' | '/notes/$noteId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ObjectsRoute: typeof ObjectsRoute
  SettingsRoute: typeof SettingsRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ObjectsRoute: ObjectsRoute,
  SettingsRoute: SettingsRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/objects",
        "/settings",
        "/notes/$noteId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/objects": {
      "filePath": "objects.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/notes/$noteId": {
      "filePath": "notes/$noteId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
