name: Release
on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - id: semver-tag
        uses: gandarez/semver-action@master
        with:
          branching_model: "git-flow"
      - name: "Created tag"
        run: echo "Version ${{ steps.semver-tag.outputs.semver_tag }}"
