name: Git Version

on:
  push:
    branches:
      - main
      - release

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v2.0.1
        with:
          versionSpec: '6.x'
      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v2.0.1
        with:
          useConfigFile: true
    outputs:
      version: ${{ steps.version.outputs.SemVer }}

  publish:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: '--bundles nsis'

    runs-on: ${{ matrix.platform }}
    needs: version
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Change Version (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          jq '.version = "${{ needs.version.outputs.version }}"' package.json | Out-File -Encoding utf8 package.json.tmp
          mv -Force package.json.tmp package.json
      
      - name: Change Version (Unix)
        if: matrix.platform != 'windows-latest'
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ needs.version.outputs.version }}\"/" package.json

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: yarn install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'Cortex v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: ${{ github.ref != 'refs/heads/release' }}
          args: ${{ matrix.args }}

